# This workflow will build docker containers and publish them to Google Container Registry
#

name: Build and Publish to GCR - DEV

on:
  push:
    branches:
      - master
      # - dev
      # - k8s-istio-opa

# Environment variables available to all jobs and steps in this workflow
# env:
#   GCP_PROJECT: wellostack
#   #   GCP_EMAIL: ${{ secrets.WELLOSTACK_SA_EMAIL }}
#   # GITHUB_SHA: ${{ github.sha }}
#   TAG: ${{ github.sha }}
  # TAG: latest
  # TAG: dev
#   GKE_ZONE: us-west1-a
#   GKE_CLUSTER: example-gke-cluster
#   IMAGE: gke-test
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      - name: Use Application Token to create a release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        

